services:
  ft8modem:
    build:
      context: .
      target: final
      args:
        FT8MODEM_SOURCE_ARCHIVE_URL: 'https://www.kk5jy.net/ft8modem/Software/ft8modem-20250607-1.0.10195.tar.gz'
        FT8MODEM_SOURCE_ARCHIVE_SHA256: '2992fa23db13d637e1ae88542f781fe6e12ebf16ee9305981962e119ddcc861d'
      tags:
        - docker.io/philipreinken/ft8modem:latest
        - docker.io/philipreinken/ft8modem:1.0.10195