services:
  ft8modem:
    build:
      context: .
      target: final
      args:
        FT8MODEM_SOURCE_ARCHIVE_URL: 'https://www.kk5jy.net/ft8modem/Software/ft8modem-20250607-1.0.10195.tar.gz'
        FT8MODEM_SOURCE_ARCHIVE_SHA256: '2992fa23db13d637e1ae88542f781fe6e12ebf16ee9305981962e119ddcc861d'
      tags:
        - docker.io/philipreinken/ft8modem:latest
        - docker.io/philipreinken/ft8modem:1.0.10195
    user: "1000:1000"
    group_add:
      - "audio"
    environment:
      PULSE_SERVER: "unix:${XDG_RUNTIME_DIR}/pulse/native"
    volumes:
      - "${XDG_RUNTIME_DIR}/pulse/native:${XDG_RUNTIME_DIR}/pulse/native"
      - "${HOME}/.config/pulse/cookie:/home/linhpsdr/.config/pulse/cookie"
    devices:
      - "/dev/snd"