x-ft8modem-source:
  name: ft8modem
  license: GPL-3.0
  homepage: https://www.kk5jy.net/ft8modem/
  filename: &ft8modem_filename ft8modem-20250526-1.0.10161.tar.gz
  filename_base: &ft8modem_filename_base ft8modem-20250526-1.0.10161
  source_archive: &ft8modem_source_archive https://www.kk5jy.net/ft8modem/Software/ft8modem-20250526-1.0.10161.tar.gz

services:
  base:
    build:
      context: .
      dockerfile_inline: |
        FROM debian:bookworm-slim
  build_deps:
    build:
      context: .
      dockerfile_inline: |
        FROM base
        
        RUN <<EOF
          apt-get update && apt-get install -y \
            librtaudio6 \
            librtaudio-dev \
            libsndfile1-dev \
            cmake \
            git \
            autoconf \
            libtool \
            automake \
            build-essential \
            wsjtx
          
          apt-get clean
          rm -rf /var/lib/apt/lists/* /tmp/*
        EOF
      additional_contexts:
        base: service:base
  ft8modem_source:
    build:
      context: .
      args:
        FT8MODEM_SOURCE_FILENAME: *ft8modem_filename
        FT8MODEM_SOURCE_FILENAME_BASE: *ft8modem_filename_base
        FT8MODEM_SOURCE_DEST: /ft8modem
      dockerfile_inline: |
        FROM base
        
        ARG FT8MODEM_SOURCE_FILENAME
        ARG FT8MODEM_SOURCE_FILENAME_BASE
        ARG FT8MODEM_SOURCE_DEST
        
        COPY --from=ft8modem_source_archive /$$FT8MODEM_SOURCE_FILENAME /tmp/
        
        RUN <<EOF
          tar -xzf /tmp/$$FT8MODEM_SOURCE_FILENAME -C /tmp/
          mv /tmp/$$FT8MODEM_SOURCE_FILENAME_BASE $$FT8MODEM_SOURCE_DEST
          rm -f /tmp/$$FT8MODEM_SOURCE_FILENAME
        EOF
      additional_contexts:
        base: service:base
        ft8modem_source_archive: *ft8modem_source_archive
  build_ft8modem:
    build:
      context: .
      dockerfile_inline: |
        FROM build_deps
        
        COPY --from=ft8modem_source /ft8modem /ft8modem
        
        WORKDIR /ft8modem
        
        RUN <<EOF
          make
          make install
        EOF
      additional_contexts:
        build_deps: service:build_deps
        ft8modem_source: service:ft8modem_source
  final:
    build:
      context: .
      dockerfile_inline: |
        FROM base AS final
        
        COPY --from=build_ft8modem /ft8modem/ft8modem /usr/local/bin/
        COPY --from=build_ft8modem /ft8modem/lib/* /usr/local/lib/
        
        ENTRYPOINT ["/usr/local/bin/ft8modem"]
        CMD ["--help"]
      target: final
      additional_contexts:
        base: service:base
        build_ft8modem: service:build_ft8modem
  ft8modem:
    extends:
      service: final
    build:
      tags:
        - docker.io/philipreinken/ft8modem:latest