services:
  ft8modem:
    build:
      context: .
      target: final
      args:
        FT8MODEM_SOURCE_ARCHIVE_URL: 'https://www.kk5jy.net/ft8modem/Software/ft8modem-20250607-1.0.10195.tar.gz'
        FT8MODEM_SOURCE_ARCHIVE_SHA256: '2992fa23db13d637e1ae88542f781fe6e12ebf16ee9305981962e119ddcc861d'
      tags:
        - docker.io/philipreinken/ft8modem:latest
        - docker.io/philipreinken/ft8modem:1.0.10195
      platforms: # In case of problems, see: https://docs.docker.com/build/building/multi-platform/#prerequisites
        - linux/amd64
        - linux/arm64
    user: "1000:1000"
    group_add:
      - "audio"
    environment:
      PULSE_SERVER: "unix:${XDG_RUNTIME_DIR}/pulse/native"
    volumes:
      - "${XDG_RUNTIME_DIR}/pulse/native:${XDG_RUNTIME_DIR}/pulse/native"
      - "${HOME}/.config/pulse/cookie:/home/ft8modem/.config/pulse/cookie"
    tmpfs:
      - "/run/user/1000/ft8modem:mode=755,uid=1000,gid=1000"
    devices:
      - "/dev/snd"
    network_mode: "host"

  ft8cat:
    extends:
      service: ft8modem
    entrypoint: "/usr/local/bin/ft8cat"

  af2udp:
    extends:
      service: ft8modem
    entrypoint: "/usr/local/bin/af2udp"

  ft8collect:
    extends:
      service: ft8modem
    entrypoint: "/usr/local/bin/ft8collect"

  ft8encode:
    extends:
      service: ft8modem
    entrypoint: "/usr/local/bin/ft8encode"

  ft8qso:
    extends:
      service: ft8modem
    entrypoint: "/usr/local/bin/ft8qso"

  ft8report:
    extends:
      service: ft8modem
    entrypoint: "/usr/local/bin/ft8report"

  ft8sdr:
    extends:
      service: ft8modem
    entrypoint: "/usr/local/bin/ft8sdr"

  ft8swl:
    extends:
      service: ft8modem
    entrypoint: "/usr/local/bin/ft8swl"

  # FIXME: Service exits; figure out process mgmt.
  work:
    extends:
      service: ft8modem
    entrypoint: "/usr/local/bin/ft8qso"
    command: ["ft8cat", "-s", "-a", "/home/ft8modem/ALL.txt", "ft8modem", "ft8", "4"] # configure to your needs via compose.override.yaml

