name: ci

on:
  push:

jobs:
  bake:
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub
        if: ${{ github.ref == 'refs/heads/main' || github.ref_type == 'tag' }}
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/bake-action@v6
        with:
          push: ${{ github.ref == 'refs/heads/main' || github.ref_type == 'tag' }}
          set: |
            ${{ github.ref_type == 'tag' && format('*.tags={0}/ft8modem:{1}', vars.DOCKERHUB_USERNAME, github.ref_name) }}
            *.tags=${{ vars.DOCKERHUB_USERNAME }}/ft8modem:latest