name: Deploy

on:
  push:
    path-ignore:
      - Makefile
      - README.md
      - LICENSE
      - .gitignore
    branches:
      - main
    tags:
      - '*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: 'Docker Hub'
    steps:
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ vars.DOCKERHUB_USERNAME || github.actor }}/ft8modem:latest

      - name: Login to DockerHub
        if: ${{ github.ref == 'refs/heads/main' || github.ref_type == 'tag' }}
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/bake-action@v6
        with:
          files: |
            ./compose.yaml
            cwd://${{ steps.meta.outputs.bake-file }}
          push: ${{ github.ref == 'refs/heads/main' || github.ref_type == 'tag' }}
          targets: ft8modem